# Generated by Django 2.0.2 on 2022-03-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamiento',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
