# Generated by Django 2.0.2 on 2022-03-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0002_estacionamiento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamiento',
            name='tipo2',
            field=models.CharField(choices=[('A', 'Auto'), ('B', 'Bus'), ('M', 'Moto'), ('C', 'Bicicleta')], max_length=3, null=True),
        ),
    ]
