# Generated by Django 2.0.2 on 2022-03-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0003_estacionamiento_tipo2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamiento',
            name='piso',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
    ]
